name: Erlang CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:22.0.7

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar3 compile
    - name: Run dialyzer
      run: rebar3 dialyzer
    - name: Run xref
      run: rebar3 xref
